name: lab2_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  floor: ^1.5.0
  sqflite: ^2.0.0+3
  path: ^1.8.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  floor_generator: ^1.4.0
  mockito: ^5.1.0


flutter:
  uses-material-design: true
  assets:
    - Images/question-mark.png
    - Images/idea.png
    - Images/stop.png
